name: Publish package to NuGet

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nuget.yml"
      - "src/Misskey.Net/**"
      - "src/CSharpWrapper/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build CSharpWrapper
        run: dotnet build --configuration Release ./src/CSharpWrapper/CSharpWrapper.csproj

      - name: Build Misskey.Net
        run: dotnet build --configuration Release ./src/Misskey.Net/Misskey.Net.fsproj

      - name: Test
        run: dotnet test --configuration Release
        working-directory: .

      - name: Pack
        run: dotnet pack --configuration Release ./src/Misskey.Net/Misskey.Net.fsproj --no-restore --output nupkgs

      - name: Publish
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
