name: Publish package to NuGet

on:
  push:
    branches:
      - main
    paths:
      - "src/Misskey.Net/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        run: dotnet build --configuration Release
        working-directory: .

      - name: Test
        run: dotnet test --configuration Release
        working-directory: .

      - name: Pack
        run: dotnet pack --configuration Release --no-build --no-restore --output nupkgs
        working-directory: .

      - name: Publish
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
        working-directory: .
