name: Publish package to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        run: dotnet build --configuration Release
        working-directory: .

      - name: Test
        run: dotnet test --configuration Release
        working-directory: .

      - name: Pack
        run: dotnet pack --configuration Release --ou nupkg
        working-directory: .

      - name: Publish
        run: find . -type f -name '*.nupkg' -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        env:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
        working-directory: ./src/nupkg
