name: Publish package to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        run: dotnet build --configuration Release
        working-directory: .

      - name: Test
        run: dotnet test --configuration Release
        working-directory: .

      - name: Pack
        run: dotnet pack --configuration Release -o nupkg
        working-directory: .

      - name: Publish
        uses: nuget/nuget-push@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: ${{ github.ref }}
          source: https://api.nuget.org/v3/index.json
          package: ./nupkg/*.nupkg
